apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://gitlab.com/JackeyyLove/student-management-backend.git'
      path: helm-chart
      targetRevision: HEAD
      helm:
        valueFiles:
          -  https://gitlab.com/JackeyyLove/vdt24-config-api/raw/main/values.yaml
    - repoURL: 'https://github.com/JackeyyLove/VDT24-HelmChart-DB.git'
      path: .
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
    
    - repoURL: 'https://gitlab.com/JackeyyLove/student-management-frontend.git'
      path: helm-chart
      targetRevision: HEAD
      helm:
        valueFiles:
          - https://gitlab.com/JackeyyLove/vdt24-config-web/raw/main/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true